### ISSUE TITLE
[Config] Enable flexibility and simplicity in configuring  Tracetest 

### ISSUE THREAD

**Issue by kdhamric** [kubeshop/tracetest#1937]
Goals:

- minimize the complexity of configuring Tracetest
- enable single command automated install & configuration
- minimize complexity in our documentation / blog posts
- enable configuration via the UI & CLI after installation
- make the tracetest.yaml file so it is minimized to the bare minimum

Tasks:
- [ ] Implement Viper
- [ ] Move analytics into UI
- [ ] Enable setting analytics via CLI
- [ ] Move polling settings into the UI
- [ ] Enable setting polling via the CLI
- [ ] Move demo configurations into the UI
- [ ] Enable setting demo configuration via the CLI
- [ ] Ability to provision Tracetest server configuration automatically
- [ ] Update examples to use new install method / config
- [ ] Update docs to use new install method / config
- [ ] Discuss how to handle exporter section in config file

**Comment by schoren** [comment]
# Proposal

We can split the config into 3 main categories: 
- `server` config includes values that are **required** to start a server instance,
- `user` config includes values more dynamic in nature, and very user oriented.
- `initialization` used to load initial configs when first installing. 

In detail:

### Server Config
Included values:
- postgres:
	- host
	- user
	- pasword
	- database
	- params
- server:
	- port
	- pathPrefix
- experimental features (list of enabled, temporary, feature flags)
- internal telemetry: (required for internal testing)
	- enabled
	- otelcollector address

### User config

- Data Stores
- analytics enabled
- Trace Pull Strategies:
	- Timeout:
		- max wait time for trace
		- retry delay
- demo:
	- PokeShop
		- enabled
		- http endpoint
		- grpc endpoint
	- otel store
		- enabled
		- Frontend endpoint
		- ProductCatalog endpoint
		- Cart endpoint
		- Checkout endpoint

### Initialization
must be kept equal to  `user` config.

## Where each config should live

- `server` config can be stored in ENV vars, config file, or passed via flags on server startup
- `user` settings must be kept in DB, so they can easily be updated via UI.
- `initialization`  should be a yaml file matching the `user` settings structure. It can be read on first run and inserted into DB, and then ignored for the rest of the runs. This is useful for fleet or automated initialization.
Some systems don’t make including a file easy, so we can also include an ENV var mechanism. Users define an env var, like `TRACETEST_INITIAL_CONFIG` that includes a base64 encoded version of the desired yaml initialization config. If tracetest detects this variable, it decodes it and continues as if it was reading the file from disk.
There’s a point to be made that users in need of automatic initialization might benefit from using this same mechanism for updating settings. See [[/Automated config updates]] for details.


## server config details
It’s practical to allow multiple methods for overriding configuration of a server instance. In general, most cli follows this hierarchy:
* flag
* env
* config file
* default

### yaml config
```yaml
postgres: 
  database: tracetest
  host: localhost
  user: user
  password: passwd
  port: 5432 
  params: "sslmode=disable"
server:
  port: 11633
  pathPrefix: /
experimentalFeatures: []
internalTelemetry:
  enabled: true
  otelcollectorEndpoint:  otel-collector.tracetest
```

### ENV overwriting
```bash
TRACETEST_POSTGRES_DATABASE=tracetest
TRACETEST_POSTGRES_HOST=localhost
TRACETEST_POSTGRES_USER=user
TRACETEST_POSTGRES_PASSWORD=passwd
TRACETEST_POSTGRES_PORT=5432 
TRACETEST_POSTGRES_PARAMS="sslmode=disable"
TRACETEST_SERVER_PORT=11633
TRACETEST_SERVER_PATH_PREFIX="/"
TRACETEST_EXPERIMENTAL_FEATURES="a b"
TRACETEST_INTERNAL_TELEMETRY_ENABLED=true
TRACETEST_INTERNAL_TELEMETRY_OTELCOLLECTOR_ENDPOINT=otel-collector.tracetest
```

### Flags
```bash
tracetest \
  --postgres.database=tracetest \
  --postgres.host=localhost \
  --postgres.user=user \
  --postgres.password=passwd \
  --postgres.port=5432  \
  --postgres.params="sslmode=disable" \
  --server.port=11633
  --server.pathPrefix=/
  --experimentalFeatures=[a, b]
  --internalTelemetry.enabled=true
  --internalTelemetry.otelcollectorEndpoint=otel-collector.tracetest
```

## Initial Config file
```yaml
analyticsEnabled: true

tracePollStrategies:
  timeout:
    maxWaitTimeForTrace: 30s
    retryDelay: 500ms

dataStores:
  - type: jaeger
    jaeger:
      endpoint: jaeger-query:16685
      tls:
        insecure: true

demo:
  pokeshop:
    enabled: true
    httpEndpont: http://demo-api:8081
    grpcEndpont: demo-api:8082
  
  otelStore:
    enabled: true
    frontendEndpoint: http://otel-frontend:8084
    productCatalogEndpoint: otel-productcatalogservice:3550
    cartEndpoint: otel-cartservice:7070
    checkoutEndpoint: otel-checkoutservice:5050
```


## Automated config updates
The problem we had with automatic config updates is that we need to somehow merge any config generated from the UI with the one given in the updated config.
In the case where you would want to use automatic config updates, you probably don’t care about the changes made in the UI. That being said, it’s not a great idea to have the server just killl manual settings without any warning if you didn’t realize you triggered an automated update.

**Solution:**
We could provide a server flag `--allow-auto-update` . If the flag is present, we can force the update of settings from an init file.

**Comment by mathnogueira** [comment]
In the near future, we want to provide a way for users to be able to change the polling strategy depending on the test. Tests that rely on long-running operations should have long polling strategies while quick tests should use a fast polling strategy.

I wonder if we could support having multiple polling strategies in the initial config as well

```yaml
tracePollStrategies:
  timeout:
    maxWaitTimeForTrace: 30s
    retryDelay: 500ms
```

becomes either an array of strategies or a map of strategies.

**Comment by schoren** [comment]
@mathnogueira exactly, that's the idea! Imagine we have a startegy to end when certain span appears in the trace. It could be configured like this:

```yaml
tracePollStrategies:
  # this one is still valid
  timeout:
    maxWaitTimeForTrace: 30s
    retryDelay: 500ms

  # but we also have this one:
  spanMatch:
    selector: span[name="final span"]
    condition: tracetest.selected_spans.count = 1
```

`timeout` and `spanMatch` are available strategies.

**Comment by kdhamric** [comment]
I think we will need to be able to name the strategy. For instance, I may have 2 instances of a tracePollStrategy that relies on the 'timeout' technique. One may be for really long processes, so I would call it 'Long running processes' and might set the maxWaitTimeForTrace to 60m, and a retryDelay of 60 seconds. I may have a second that is 'Fast API polling' set to happen quickly.

I think we will be able to associate a test with a polling strategy at some point.

**Comment by kdhamric** [comment]
https://github.com/kubeshop/tracetest/issues/1626 is also related to this issue.

**Comment by schoren** [comment]
ok, let's take that approach. So the final thing would look like this:

```yaml
analyticsEnabled: true

polling:
   profiles:
    - timeout: #this is the name
        name: Long running test
        strategy: sameSpanCount
        config:
          executions: 3 # if the number of spans is the same in 3 subsequent executions, the trace is marked as complete
          retryDelay: 60s
          timeout: 120m
          
dataStores:
  - type: jaeger
    jaeger:
      endpoint: jaeger-query:16685
      tls:
        insecure: true

demo:
  pokeshop:
    enabled: true
    httpEndpont: http://demo-api:8081
    grpcEndpont: demo-api:8082
  
  otelStore:
    enabled: true
    frontendEndpoint: http://otel-frontend:8084
    productCatalogEndpoint: otel-productcatalogservice:3550
    cartEndpoint: otel-cartservice:7070
    checkoutEndpoint: otel-checkoutservice:5050
```

Keep in mind that for this particular story, we should only focus on configuration and not actual functionality. I say this because we can make the config look like that, but adding support for multiple profiles (including defining a default one) would be out of scope of this issue.

**Comment by schoren** [comment]
@kdhamric had this great idea. Since we'll be adding support for CLI to update these configs, we'll need to add new yaml formats similar to [datastores]. So, instead of having to maintain those yaml format and this initialization format, we can just use the main format, and have the initialization mechanism use a bunch of contactenated yamls, as you might do on k8s.

For example, the previous example could be rewriten as:
```yaml
---
type: PollingProfile
spec:
  name: Long running test
  strategy: sameSpanCount
  isDefault: true
  specs:
    executions: 3
    retryDelay: 60s
    timeout: 120m

---
type: DataStore
spec:
  name: development
  type: jaeger
  isDefault: true
  jaeger:
    endpoint: 127.0.0.1:16685
    tls:
      insecure: true

---
type: Demo
spec:
  type: pokeshop
  enabled: true
  specs:
    httpEndpont: http://demo-api:8081
    grpcEndpont: demo-api:8082

---
type: Demo
spec:
  type: otelstore
  enabled: true
  specs:
    frontendEndpoint: http://otel-frontend:8084
    productCatalogEndpoint: otel-productcatalogservice:3550
    cartEndpoint: otel-cartservice:7070
    checkoutEndpoint: otel-checkoutservice:5050

---
type: Config
spec:
  analyticsEnabled: true
```

This has a bunch of benefits:
1. we are reusing existing things
2. more flexibility. we could easily allow users to also configure intiialization tests, transaction, environments, anything that follows this format.
3. extensibility. As we add new things that follow this yaml format, they can seamlessly be integrated to the init script

Thoughts?

**Comment by kdhamric** [comment]
In addition to supporting a concatenated file, we may want a command line option for 'import every thing in directory X' so we can have resource files there and have Tracetest load them when run with an initialization flag.

Putting all the config files and tests in one file and then encoding it will support @xoscar's use case for serverless.

**Comment by danielbdias** [comment]
I like the idea of typing these resources! But I have one comment about the `demo` type: we only use the naming "Demo" internally, but in our UI we give emphasis to "Examples", which could be confusing for newcomers. Should we continue calling it "Demo"?

**Comment by schoren** [comment]
@danielbdias that is a good point. Taking it even further, does anyone imagine having "api presets" as an expanded +concept?

Example: We are a team working on QAing a bank api, which have lots of endpoints in GRPC, http, etc. It would be great if we could have a list of available endpoints preconfigured, so you would only need to modify some specific values for each tests, and write the tests itself. Also might be helpful when creating transactions.

In this case, we could even rename it to `Preset` or something like that, and if needed we can expand the concept later.

Thoughts?

**Comment by adnanrahic** [comment]
I _really_ love this. It will improve user onboarding massively. Mega job documenting everything as well @schoren. 🔥

**Comment by xoscar** [comment]
Hey @schoren I really like this approach and even better with the updated changes around the entry formats for data stores, polling profiles, etc.

I also like the idea of using `base64` to encode Env variables 👀 

I have some ideas about the code architecture. When thinking about how to solve the configuration pain points we have in the app I came up with the idea of having a more "abstracted" way of dealing with our configuration, it includes the following improvements:
 - **Source agnostic.** As we move things from memory/file base to DB, we can avoid coupling that to the usage.
 - **Single source of truth.** Avoiding making Database queries for configuration values like we do here: https://github.com/kubeshop/tracetest/blob/main/server/executor/poller_executor.go#L82
 - **Singleton.** Avoiding the config instance being tossed around the different files, we can create a singleton approach that will be used across the app
 - **Hot reload.** I think we can easily implement a hot reload mechanism by following this approach.

## Generating Config Instance Singleton

```mermaid
graph TD
  A[Init App] -->B(Set Defaults)
  B -->|Read| D[Env Vars]
  B -->|Read| E[Flags]
  B -->|Read| F[Config file]
  D -->G[fa:fa-industry Generate Config Singleton]
  E -->G
  F -->G
  G -->H[Validate]
  H -->I{IsValid}
  I --> |No|J[Throw Error]
  I --> |Yes|K[FIN]
  J --> K
```

## Config Usage DataFlow

```mermaid
graph TD
  App[App] --> ConfigSingleton(Config Singleton)
  Poller --> ConfigSingleton
  Executor --> ConfigSingleton
  Controller -->ConfigSingleton
  ConfigSingleton --> |read/write| DataStoreRepo(Data Store Repository)
  ConfigSingleton --> |read/write| ConfigRepository(Config Repository)
  ConfigRepository --> DB(fa:fa-database Database)
  DataStoreRepo --> DB
  ConfigSingleton --> |read/write| Memory(fa:fa-memory Memory)
```

Let me know what you think!

**Comment by schoren** [comment]
@xoscar thanks for the very thorough proposal. As a general principal, I would avoid the usage of the `singleton` as it is generally considered an anti-pattern, because in it's original definition, it goes against the Dependency Injection and Inversion of Control patterns.

That being said, I will be creating a config repository, that internally will be a wrapper around viper. That config repo will only handle `server` configs, since those are the only ones that needs to support multiple config sources. It can be used as a pseudo singleton (in the sense of having only one instance per runtime) but it also supports initialization of multiple equivalent objects.

I don't think configuration should be only read on startup, but should be read any time it's required by a consumer, like we did with DataStores. We used to have "static" on-startup-loaded DataStores that got passed around as part of the config. This proved to be a limiting approach, so we moved it to a "read when required" approach. So now the dataStore config is read each time a poller needs to start polling from a data source. If a user updates the dataSource config between one test run and another, each one could have a totally different config without the server skipping a beat.

The rest of the configurations should stop being considered "configuration" in the sense of setup prerequisites to start a service, and start being considered plain old data entities on its own. Also we'll be adding support for multiple similar (but internally very different) file formats. There's a generalization waiting to be discovered there. I want to explore the idea of having some kind of "config (replace this word) repository" where packages can register "file formats" and handlers for it, so packages only need to care about their specific task and nothing else.

**Comment by xoscar** [comment]
@schoren thanks for the explanation man. I didn't know we were targeting a dependency-injection pattern but its good to know that, have you considered using something like https://github.com/uber-go/dig to automate the passing of the parameters and generating the instances for you?

In that case, it can solve the problem of drilling down dependencies from the top of the three to nested structs.

As per the configuration, I agree that we should be able to read-write during runtime not only during execution, I just think that having an abstraction layer between the "settings" data and the services could be useful to avoid coupling and in case we want to change the internal behavior.

To your last point, I think that's a great idea, I think we just need to have a clear cut between what is startup data vs runtime data so that if someone needs to update a section of it doesn't get lost.

**Comment by schoren** [comment]
I'm not a huge fan of DI frameworks, specially if they are reflection based. I found it easier to just do DI by hand, like we're doing currently. It's more explicit, less complex, and you can `ctrl click` the code to see what's actually going on.

**Comment by olha23** [comment]
design here 👉https://github.com/kubeshop/tracetest/issues/1988

**Comment by olha23** [comment]
i have a question about  'Move demo configurations into the UI' what kind of configuration we need to show exactly?

**Comment by schoren** [comment]
@olha23 `demo` configs are this:

```yaml
demo:
  pokeshop:
    enabled: true
    httpEndpont: http://demo-api:8081
    grpcEndpont: demo-api:8082
  
  otelStore:
    enabled: true
    frontendEndpoint: http://otel-frontend:8084
    productCatalogEndpoint: otel-productcatalogservice:3550
    cartEndpoint: otel-cartservice:7070
    checkoutEndpoint: otel-checkoutservice:5050
```

We have 2 sections: `PMA` and `Otel Store` (not sure if those are the names we want to display). Each section can be enabled or disabled, and then it shows a text box for each `endpoint`. So for example it could look something like this:

| PMA | [Checkbox] | Otel Demo | [Checkbox] |
|---|---|---|---|
| httpEndpoint: | [text field] | Frontend Endpoint: | [text field] |
| grpcEndpont: | [text field] | Frontend Endpoint: | [text field] |
|   |   | Product Catalog Endpoint: | [text field] |
|   |   | Cart Endpoint: | [text field] |

Does this make sense?

**Comment by schoren** [comment]
## CLI usage

`tracetest apply [resource type?] -f [file|path]` upsert any resources found in the files
`tracetest list [resource type?]`  if no Resource Type given, show all resources, grouped by type
`tracetest export [resource type?] (--id [id]?)`  prints to stdout a single yaml file with all resources, separated by ---.

### examples:
export all resources: `tracetest export`
export all tests: `tracetest export tests`
export specific test: `tracetest export tests --id 123`

`tracetest delete [resource type?] (--file [file|path]?) (--id [id]) (--force)`

### examples:
`tracetest delete tests --force`  deletes all tests skipping confirmation
`tracetest delete tests` deletes all tests, asking confirmation first
`tracetest delete tests --id 123` delete test ID 123
`tracetest delete tests --file ./example.yaml` delete the test defined in the file. If the file has no ID defined, it fails (even if run with --force


### Example resource type list

`tracetest list datastores`

| id | name | type | is default? |
|---|---|---|---|
| 123 | dev jaeger | Jaeger | * |
| 321 | prod | Tempo |   |


### Available resource types:

- environments
- data sources
- config (aka analyics)
- pooling config
- transactions
- tests

## Resource ID in definition files

Same approach as tests: if file has no ID, cli "persists" the created ID into the file. users can define their ID. 

### autogenerating IDs on CI environments

- if an environment variable  CI=true  is set and the resource file doesn’t have an ID, fail with error: "looks like you’re on CI and the resource doesn’t have an explicit ID. fix it"
- else, inject the created resource ID (from the server) into the file,  showing a visible warning "The resource file does not have an explicit ID, so we’re adding one"
