### ISSUE TITLE
[Analyzer] Configuration - Backend

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#2773]
As part of the configuration changes, we need to allow users to update different sections of the analyzer, which include:
- Plugin enabled/disabled status
- Rule error levels
- Rule weights for score calculation

As well as to use the configurations when executing the analyzer step for each of the test runs

#### Acceptance Criteria
**AC1**
As a user configuring the analyzer
I should be able to configure which plugins I want to enable for my test runs

**AC2**
As a user configuring the analyzer
I should be able to set the critical level for each of the rules within a plugin
and the options should be `error`, `warning`, `skipped`

**AC3**
As a user configuring the analyzer
I should be able to set the weight for each of the rules within a plugin
Having the sum of the weights to be 100%

**AC4**
As a user executing a test run
And I see the analyzer results
I should only see the results from the plugins I have enabled

**AC5**
As a user executing a test run
And I see the analyzer results
The global score should be calculated based on the enabled plugins and the rules with `error` or `warning` critical levels

**AC6**
As a user executing a test run
And I see the analyzer results
I should see the critical level result for each of the rules based on the config

```[tasklist]
### Tasks
- [ ] Update OpenAPI specs to reflect the new contract
- [ ] Update Analyzer resource to support the new configuration
- [ ] Update Analyzer result model to persist the new list of fields
- [ ] Implement Runner changes to use the new configuration values
```
