### ISSUE TITLE
[Analyzer] Configuration - Frontend

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#2774]
As part of the configuration changes, we need to allow users to update different sections of the analyzer, which include:
- Plugin enabled/disabled status
- Rule error levels
- Rule weights for score calculation

As well as to use the configurations when executing the analyzer step for each of the test runs

#### Acceptance Criteria
**AC1**
As a user configuring the analyzer
I should be able to configure which plugins I want to enable for my test runs

**AC2**
As a user configuring the analyzer
I should be able to set the critical level for each of the rules within a plugin
and the options should be `error`, `warning`, `skipped`

**AC3**
As a user configuring the analyzer
I should be able to set the weight for each of the rules within a plugin
Having the sum of the weights to be 100%

**AC4**
As a user executing a test run
And I see the analyzer results
I should only see the results from the plugins I have enabled

**AC5**
As a user executing a test run
And I see the analyzer results
The global score should be calculated based on the enabled plugins and the rules with `error` or `warning` critical levels

**AC6**
As a user executing a test run
And I see the analyzer results
I should see the critical level result for each of the rules based on the config

```[tasklist]
### Tasks
- [ ] Implement new contract based on BE changes
- [ ] Update Analyzer section to display rule critical status
- [ ] Update Analyzer settings form to match new configuration
```

**Comment by xoscar** [comment]
@olha23 do you mind taking a look at this?

**Comment by olha23** [comment]
@xoscar do we need to show general Minimum score in settings?

**Comment by olha23** [comment]
@xoscar can you check this please https://www.figma.com/file/nXy4eBvpiQ3P4Jer0ogJOw/v0.11-release?type=design&node-id=530%3A14948&mode=design&t=zwXpU1uVjzHXlJSE-1


and I’m not sure what i need to do with analyzer results

**Comment by olha23** [comment]
@xoscar i updated mockups based on our conversation https://www.figma.com/file/nXy4eBvpiQ3P4Jer0ogJOw/v0.11-release?type=design&node-id=530%3A14948&mode=design&t=lIXWdTgS9EnSW0Bg-1
