### ISSUE TITLE
[Analyzer] Global Configuration - Test Run Failure Gates - Backend

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#2776]
As part of the changes to support a specific failure point for test runs, we need to update the backend to support these changes.

#### Acceptance Criteria

**AC1**
As a user configuring the server
I should be able to set the global gates for test runs
Which should be a list of any of the following
- test specs
- analyzer score
- analyzer rule

**AC2**
As a user executing a test
I should be able to attach the gates to the request
Which overrides the global configuration

**AC3**
As a user that executed a test
I should see the configuration of the gates used for the run
And the result of such calculation passed/failed

**AC4**
As a user that executed a test
The test run execution should not stop if any of the gates are marked as failed

**AC5**
As a user that executed a test
The test run should include the information about the client source of the test trigger

```[tasklist]
### Tasks
- [ ] Update the openAPI specs to support failure point and result
- [ ] Update Configuration resource to support failure point
- [ ] Allow failure point config during the run test request
- [ ] Calculate failure result based on the configuration/request
- [ ] Persist failure configuration and result at the test run level
- [ ] Persist the source of the test run (CLI/FE/REST) at the test run level
```
