### ISSUE TITLE
[Analyzer] Global Configuration - Test Run Failure Gates - Frontend

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#2777]
As part of the changes to support a specific failure point for test runs, we need to update the backend to support these changes.

#### Acceptance Criteria

**AC1**
As a user configuring tracetest
I should be able to set the globally required gates for the test runner configuration
Which should be a list of any of the following
- test specs
- analyzer score
- analyzer rule

**AC2**
As a user that executed a test
I should see the configuration for the required gate used for the run
And the result of such calculation passed/failed

**AC3**
As a user that executed a test
And I execute a test run that yields an analyzer rule error
I should see the analyzer results section showing the filed rule error similar to the score

```[tasklist]
### Tasks
- [ ] Update models and contracts based on the BE changes
- [ ] Implement new inputs for the test runner resource settings
- [ ] Display the configuration of the required gate used for test runs
- [ ] Update Failed/Success information for test runs based on the result
- [ ] Implement analyzer rule failure-based information
```

**Comment by xoscar** [comment]
Adding use cases
More information about settings
Some diagrams

**Comment by xoscar** [comment]
@olha23 I have updated this issue ACs

I had a conversation with @kdhamric and what we need to do for the FE are the following things:
1. Create a new settings page for the test runner resource to allow users to configure the required gates
2. Show the configuration of the required gates for test runs on the test run details page and in the cards
3. Update the analyzer results to show a failure state in case one of the error level analyzer rule fails (currently we only do this for score)


Test runner resource sample
```
{
  "type": "TestRunner",
  "spec": {
    "id": "current",
    "name": "default",
    "requiredGates": ["test-specs", "analyzer-rules", "analyzer-score"]
  }
}
```

Where the required gates are the only thing that can be updated, and the available values are just those three ("test-specs", "analyzer-rules", "analyzer-score")

**Comment by xoscar** [comment]
Use cases:

# 1
The user configures the test runner to fail on the analyzer score
The user then executes a test from the UI that ends up yielding a score below what was configured in the analyzer settings
The test run execution should be completed, but the test run information should show the test run as failed

# 2
The user configures the test runner to fail on the analyzer rules
The user then executes a test from the CLI that ends up yielding an analyzer rule error
When viewing the test run from the UI (card, details) the result should be marked as  "failed"

# 3
The user configures the test runner to fail on the analyzer rules, analyzer score and test specs
The user then executes a test from the UI that doesn't yield an error either from the analyzer or the test specs
When viewing the test run from the UI (card, details) the result should be marked as  "success"

# 4
The user configures the test runner to fail on the analyzer rules, analyzer score and test specs
The user then executes a test from the UI that yields an error from the test specs
When viewing the test run from the UI (card, details) the result should be marked as  "failed"

**Comment by olha23** [comment]
thanks for the update, working on it

**Comment by olha23** [comment]
@xoscar can you check the mockups here https://www.figma.com/file/nXy4eBvpiQ3P4Jer0ogJOw/v0.11-release?type=design&node-id=667%3A17941&mode=design&t=05dt90QAjqYQxLpv-1 and leave your comments please ?
