### ISSUE TITLE
Rename Transactions to TestSuites

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#3001]
As part of the changes that will impact the future of the Tracetest project, we want to change the `transactions` name to `test suites` as its better suited for the set of features and changes that are coming soon
```[tasklist]
### Tasks
- [x] Update database tables to use test suites
- [x] Validate that backwards compability works as expected
- [x] Update the resources
- [x] Update the CLI
- [x] Update the FE
- [ ] Update the Docs
```
