### ISSUE TITLE
Add Kafka trigger to Tracetest

### ISSUE THREAD

**Issue by danielbdias** [kubeshop/tracetest#3020]
Following the research done on Spike https://github.com/kubeshop/tracetest/issues/2983, on this task we will develop the trigger for Kafka streams.

- [Specifications](https://github.com/kubeshop/tracetest/issues/2983#issuecomment-1657181053)
- [UX Design](https://github.com/kubeshop/tracetest/issues/2983#issuecomment-1658132767)
- [Feature branch](https://github.com/kubeshop/tracetest/tree/feature/kafka-trigger)

```[tasklist]
### Tasks
- [x] Add OpenAPI specs for Kafka trigger
- [x] Add Kafka trigger on Tracetest Server
- [x] Add support for Kafka trigger on Tracetest CLI
- [x] Add support for Kafka trigger on Tracetest WebUI
- [x] Add support for Kafka on Pokeshop
- [x] Setup Tracetest instalation to have a quick example for Kafka
- [x] Add trace based test for Kafka trigger
- [x] Add CLI e2e tests for Kafka trigger
- [ ] Add Kafka tests on OTel demo test
- [ ] Add documentation
```

**Comment by xoscar** [comment]
Hey @danielbdias is this something we can close?

**Comment by danielbdias** [comment]
Yes! @adnanrahic made the documentation about Kafka, and I'll add these tests on OTel soon (creating a ticket just for it).
