### ISSUE TITLE
Support for var as template

### ISSUE THREAD

**Issue by xoscar** [kubeshop/tracetest#3052]
As we are moving away from using environments, we have to also start supporting the `var` prefix as part of the template inputs for all requests, assertions and outputs, including the CLI.

#### Acceptance criteria

**AC1**
As a user creating a new test from the UI
I should be able to use the keyword `var` on the different inputs
And when executing the test the values should be replaced by the selected variable set values

**AC2**
As a user creating a new test from the UI
I should be able to use the keyword `var` on the different inputs
And if the selected variable set doesn't have the values
I should be able to manually add them

**AC3**
As a user creating a new test from the CLI
I should be able to use the keyword `var` on the different inputs
And when executing the test the values should be replaced by the selected variable set values

**AC4**
As a user creating a new test from the CLI
I should be able to use the keyword `var` on the different inputs
And if the selected variable set doesn't have the values
I should be able to manually add them

```[tasklist]
### Tasks
- [ ] Update the server to support the keyword `var`
- [ ] Update the FE to use the `var` keyword as part of the inputs
- [ ] Update the docs to stop using `env` to use `var` instead
- [ ] Validate that this feature is backwards compatible with `env`
```
