### ISSUE TITLE
Crash under heavy load

### ISSUE THREAD

**Issue by schoren** [kubeshop/tracetest#3093]
Results from investigating https://github.com/kubeshop/tracetest/issues/3066

Debugging the issue yielded 3 main problems:

```[tasklist]
### Tasks
- [ ] https://github.com/kubeshop/tracetest/issues/3095
-  [x] Postgres driver is leaking db connections
- [ ] https://github.com/kubeshop/tracetest/issues/3096
```

The main error that is easiest to reproduce is the leaking of workers. This happens because the driver implementation doesn't have a pool of workers, it just [spins new goroutines off](https://github.com/kubeshop/tracetest/blob/main/server/executor/queue_driver_postgres.go#L114). This by itself is not the cause of the panics, but it's the starting point.

The actual problem causing the panic is that we reach the max connections limit from the Postgres server. This should not happen, because we only manually start a predefined number of connections:

1. A [pgx pool](https://github.com/kubeshop/tracetest/blob/main/server/app/app.go#L144) with the default count (same number as CPU cores available) for the queues
2. A [single connection](https://github.com/kubeshop/tracetest/blob/main/server/app/app.go#L154) for the repositories and other general queries.

This means that the leaking of the workers is also generating a leaking of DB connections. Is this caused by some configuration that allows the driver to open connections at will?

On a separated track, we have an unhandled concurrent map read/write that happens from time to time:

```
fatal error: concurrent map read and map write

goroutine 289397 [running]:
github.com/kubeshop/tracetest/server/subscription.(*Manager).PublishUpdate(0x414485?, {{0xc029776340, 0x1c}, {0x0, 0x0}, {0x1dff600, 0xc02956ad00}})
	/home/runner/work/tracetest/tracetest/server/subscription/manager.go:51 +0x58
github.com/kubeshop/tracetest/server/subscription.(*Manager).Publish(0x1dff600?, {0xc029776340?, 0xc02a94cc58?}, {0x1dff600?, 0xc02956ad00?})
	/home/runner/work/tracetest/tracetest/server/subscription/manager.go:59 +0x6e
github.com/kubeshop/tracetest/server/executor.(*internalEventEmitter).Emit(_, {_, _}, {0x0, {0x1eb8ab3, 0xf}, {0x1e9de64, 0x7}, {0x1ef0894, 0x23}, ...})
	/home/runner/work/tracetest/tracetest/server/executor/eventemitter.go:41 +0x218
github.com/kubeshop/tracetest/server/executor.persistentRunner.ProcessItem({0xc00018b380, {0x230a4a0, 0xc00074d710}, {0x2305cc0, 0xc0002b8500}, 0xc000048a00, 0xc0002b6480, {0x2305420, 0xc000012a00}, {0x2305560, ...}, ...}, ...)
	/home/runner/work/tracetest/tracetest/server/executor/runner.go:149 +0xa45
github.com/kubeshop/tracetest/server/executor.Queue.Listen({0xc0002b8640, {0x2305700, 0xc000048a00}, {0x7fe62e2ddd78, 0xc000012a20}, {0x7fe62e2ddd58, 0xc000012a18}, {0x0, 0x0}, {0x0, ...}, ...}, ...)
	/home/runner/work/tracetest/tracetest/server/executor/queue.go:338 +0x664
created by github.com/kubeshop/tracetest/server/executor.(*PostgresQueueDriver).worker
	/home/runner/work/tracetest/tracetest/server/executor/queue_driver_postgres.go:114 +0x5d1
```

This issue also causes a panic, but it's not related to the load itself. The chances of this happening increases with the amount of concurrent tests running.
