### ISSUE TITLE
Support for big traces

### ISSUE THREAD

**Issue by jorgeepc** [kubeshop/tracetest#3599]
## Problems to fix:

1. UI performance
2. Trace visualization

## FE features that need to be considered:

- DAG/Timeline views
- Search in trace
- Analyzer rules span selection
- Test Specs:
    - Selector autocomplete
    - Selected spans count
    - Assertion attribute names/values
    - Results by span, span focus
- Test Outputs:
    - Selector autocomplete
    - Selected spans count
    - Attribute autocomplete

Related to #3293
```[tasklist]
### Tasks
- [ ] https://github.com/kubeshop/tracetest/issues/3601
- [ ] https://github.com/kubeshop/tracetest/issues/3602
- [ ] https://github.com/kubeshop/tracetest/issues/3603
- [ ] https://github.com/kubeshop/tracetest/issues/3604
- [ ] https://github.com/kubeshop/tracetest/issues/3605
- [ ] https://github.com/kubeshop/tracetest/issues/3614
```
